name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'The name of the new branch to create'
        required: false
        default: 'automated-update-${{ github.run_number }}'
      pr_title:
        description: 'The title for the new pull request'
        required: false
        default: 'Automated daily update: ${{ github.event.repository.name }}'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Automated daily update'
          title: ${{ github.event.inputs.pr_title }}
          body: |
            This pull request was automatically created by a scheduled or manual workflow.
            
            It contains the daily updates for the repository.
          branch: ${{ github.event.inputs.branch_name }}
          base: 'develop'
