name: Run Python Script

on:
  pull_request:
    branches:
      - main
      - develop
  
  # Add the 'workflow_dispatch' event to manually trigger the workflow
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Miniconda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.12.2'
          activate-environment: my_env
      
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run the Python script and create website files
        run: |

          # Create a directory to hold the deployable website files
          mkdir dist

          python test_script.py
          python generate_plot.py

          # Move the generated graphs to the 'dist' directory
          mv graphs/* dist/

          # Create a simple index.html to display the graphs
          echo '<html>
            <head>
              <title>Generated Graphs</title>
              <style>
                body { font-family: sans-serif; margin: 2em; }
                img { max-width: 100%; height: auto; display: block; margin-bottom: 2em; border: 1px solid #ccc; box-shadow: 2px 2px 5px rgba(0,0,0,0.1); }
              </style>
            </head>
            <body>
              <h1>Graphs from Last Run</h1>' > dist/index.html
          echo '<ul>' >> dist/index.html
          for file in dist/*.png; do
            echo "<li><img src='/$(basename "$file")' alt='$(basename "$file")'></li>" >> dist/index.html
          done
          echo '</ul></body></html>' >> dist/index.html
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./dist
